---
version: '2'
services:
  zookeeper-europe:
    image: confluentinc/cp-zookeeper:5.3.0
    hostname: zookeeper-europe
    container_name: zookeeper-europe
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  zookeeper-us:
    image: confluentinc/cp-zookeeper:5.3.0
    hostname: zookeeper-us
    container_name: zookeeper-us
    ports:
      - "2182:2182"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000

  zookeeper-metrics:
    image: confluentinc/cp-zookeeper:5.3.0
    hostname: zookeeper-metrics
    container_name: zookeeper-metrics
    ports:
      - "2183:2183"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_TICK_TIME: 2000

  broker-europe:
    image: confluentinc/cp-enterprise-kafka:5.3.0
    hostname: broker-europe
    container_name: broker-europe
    depends_on:
      - zookeeper-europe
      - broker-metrics
      - zookeeper-metrics
    ports:
      - "9091:9091"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-europe:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-europe:9091
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      # Confluent Metrics Reporter for Control Center Cluster Monitoring
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-metrics:9093
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper-metrics:2183
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'

  broker-us:
    image: confluentinc/cp-enterprise-kafka:5.3.0
    hostname: broker-us
    container_name: broker-us
    depends_on:
      - zookeeper-us
      - broker-metrics
      - zookeeper-metrics
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-us:2182'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-us:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      # Confluent Metrics Reporter for Control Center Cluster Monitoring
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-metrics:9093
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper-metrics:2183
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
  
  broker-metrics:
    image: confluentinc/cp-enterprise-kafka:5.3.0
    hostname: broker-metrics
    container_name: broker-metrics
    depends_on:
      - zookeeper-metrics
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-metrics:2183'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-metrics:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  connect-us:
    image: confluentinc/cp-enterprise-replicator:5.3.0
    hostname: connect-us
    container_name: connect-us
    depends_on:
      - zookeeper-us
      - broker-us
      - broker-metrics
    ports:
      - "8382:8382"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker-us:9092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-us
      CONNECT_REST_PORT: 8382
      CONNECT_GROUP_ID: "connect-us"
      CONNECT_PRODUCER_CLIENT_ID: "connect-worker-producer-us"
      CONNECT_CONFIG_STORAGE_TOPIC: connect-us.config
      CONNECT_OFFSET_STORAGE_TOPIC: connect-us.offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-us.status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_PLUGIN_PATH: /usr/share/java
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
      # Confluent Monitoring Interceptors for Control Center Streams Monitoring
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_BOOTSTRAP_SERVERS: broker-metrics:9093
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
      CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_BOOTSTRAP_SERVERS: broker-metrics:9093

  connect-europe:
    image: confluentinc/cp-enterprise-replicator:5.3.0
    hostname: connect-europe
    container_name: connect-europe
    depends_on:
      - zookeeper-europe
      - broker-europe
      - broker-metrics
    ports:
      - "8383:8383"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker-europe:9091'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-europe
      CONNECT_REST_PORT: 8383
      CONNECT_GROUP_ID: "connect-europe"
      CONNECT_PRODUCER_CLIENT_ID: "connect-worker-producer-europe"
      CONNECT_CONFIG_STORAGE_TOPIC: connect-europe.config
      CONNECT_OFFSET_STORAGE_TOPIC: connect-europe.offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-europe.status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_PLUGIN_PATH: /usr/share/java
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
      # Confluent Monitoring Interceptors for Control Center Streams Monitoring
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_BOOTSTRAP_SERVERS: broker-metrics:9093
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
      CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_BOOTSTRAP_SERVERS: broker-metrics:9093

  control-center:
    image: confluentinc/cp-enterprise-control-center:5.3.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - broker-metrics
      - zookeeper-metrics
      - broker-us
      - connect-us
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker-metrics:9093'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper-metrics:2183'
      CONTROL_CENTER_CONNECT_EUROPE_CLUSTER: http://connect-europe:8381
      CONTROL_CENTER_CONNECT_US_CLUSTER: http://connect-us:8382
      CONTROL_CENTER_KAFKA_EUROPE_BOOTSTRAP_SERVERS: 'broker-europe:9091'
      CONTROL_CENTER_KAFKA_US_BOOTSTRAP_SERVERS: 'broker-us:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
